### ISSUE TITLE
Help Button not showing up on one time payment portion

### ISSUE THREAD

**Issue by anishnuni** [cryptopatron/web-app#17]
Help Button not showing up on one time payment portion although it is working fine on the streaming side. Someone else should see if they can see the issue. This is on the latest commit in the anishnuni-help-modal branch.

**Comment by dgan181** [comment]
#18 fixes the issue by defining one modal component in the parent of the `one-timer` and `stream` components. 

The issue is rather surprising - not sure why it fails when `Modal` is included in the children.
